[features]
seeds = false
skip-lint = false
[programs.localnet]
web3ads = "Fg6PaFzntrJZ1Ym1FzKSAkJS2LpkuSqS1fyyKN1LL5y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/harshghodkar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
